version: '3.8'
services:
  hlm-backend:
    image: healenium/hlm-backend:3.4.4
    container_name: hlm-backend
    ports:
      - "7878:7878"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/healenium
      - SPRING_DATASOURCE_USERNAME=healenium_user
      - SPRING_DATASOURCE_PASSWORD=YDk2nmNs4s9aCP6K
      - FIND_ELEMENTS_AUTO_HEALING=true
    networks:
      - healenium

  hlm-selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: hlm-selector-imitator
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - healenium

  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - healenium

  hlm-proxy:
    image: healenium/hlm-proxy:1.4.0
    container_name: hlm-proxy
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - RECOVERY_TRIES=1
      - SCORE_CAP=.6
      - HEAL_ENABLED=true
      - SELENIUM_SERVER_URL=http://selenium-hub:4444
      - APPIUM_SERVER_URL=http://host.docker.internal:4723
      - HEALENIUM_SERVER_URL=http://hlm-backend:7878
      - HEALENIUM_SERVICE=http://hlm-backend:7878
      - IMITATE_SERVICE=http://selector-imitator:8000
      - HLM_LOG_LEVEL=debug
    volumes:
      - ./logs/:/logs
    networks:
      - healenium

  chrome:
    image: selenium/node-chrome:latest
    container_name: node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=20
    networks:
      - healenium

  edge:
    image: selenium/node-edge:latest
    container_name: node-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  firefox:
    image: selenium/node-firefox:latest
    container_name: node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - healenium

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
